In [2]:
# mlp for regression
#import libraries for plotting the results
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from matplotlib import pyplot

#import scikeras
#from scikeras.wrappers import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

from numpy import sqrt
from pandas import read_csv
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
#lode csv and turn into dataframe
df = read_csv('civil_unrest_2021-08-04-2023-08-04.csv', header=0)

In [4]:
df.head()

,event_id_cnty,event_date,year,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,tags,timestamp
0,ETH10298,28 July 2023,2023,1,Demonstrations,Protests,Protest with intervention,Protesters (Ethiopia),Former TPLF: Tigray People's Liberation Front,6,...,Mekele,13.5000,39.4667,1,Addis Maleda,National,"On 28 July 2023, over 6000 war injured former ...",0,crowd size=over 6000,1690811106
1,SAF19500,28 July 2023,2023,2,Demonstrations,Protests,Peaceful protest,Protesters (South Africa),Operation Dudula,6,...,Zwelihle,-34.4311,19.2151,1,Daily News (South Africa),National,"Around 28 July 2023 (as reported), Hermanus re...",0,crowd size=no report,1690811106
2,SAF19506,28 July 2023,2023,1,Demonstrations,Protests,Peaceful protest,Protesters (South Africa),NaN,6,...,Durban,-29.8579,31.0292,1,Daily News (South Africa),National,"On 28 July 2023, dozens of utility ratepayers ...",0,crowd size=dozens,1690811106
3,SAF19513,28 July 2023,2023,1,Demonstrations,Riots,Violent demonstration,Rioters (South Africa),NaN,5,...,Pietermaritzburg,-29.6167,30.3833,1,Citizen (South Africa),National,"On 28 July 2023, demonstrators barricaded Old ...",0,crowd size=no report,1690811106
4,SSD9374,28 July 2023,2023,2,Political violence,Violence against civilians,Attack,Unidentified Armed Group (South Sudan),NaN,3,...,Liria,4.6437,32.0797,2,Eye Radio (South Sudan),National,"Around 28 July 2023 (as reported), the adminis...",0,NaN,1690811106

In [6]:
df.shape

(378056, 31)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378056 entries, 0 to 378055
Data columns (total 31 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   event_id_cnty       378056 non-null  object
 1   event_date          378056 non-null  object
 2   year                378056 non-null  int64
 3   time_precision      378056 non-null  int64
 4   disorder_type       378056 non-null  object
 5   event_type          378056 non-null  object
 6   sub_event_type      378056 non-null  object
 7   actor1              378056 non-null  object
 8   assoc_actor_1       229866 non-null  object
 9   inter1              378056 non-null  int64
 10  actor2              103742 non-null  object
 11  assoc_actor_2       42397 non-null   object
 12  inter2              378056 non-null  int64
 13  interaction         378056 non-null  int64
 14  civilian_targeting  72810 non-null   object
 15  iso                 378056 non-null  int64
 16  region              378056 non-null  object
 17  country             378056 non-null  object
 18  admin1              378051 non-null  object
 19  admin2              368315 non-null  object
 20  admin3              156478 non-null  object
 21  location            378056 non-null  object
 22  latitude            378056 non-null  float64
 23  longitude           378056 non-null  float64
 24  geo_precision       378056 non-null  int64
 25  source              378056 non-null  object
 26  source_scale        378056 non-null  object
 27  notes               378056 non-null  object
 28  fatalities          378056 non-null  int64
 29  tags                319074 non-null  object
 30  timestamp           378056 non-null  int64
dtypes: float64(2), int64(9), object(20)
memory usage: 89.4+ MB